name: rosbackup
version: '1.0.0'
summary: RouterOS config backup tool
description: |
  Simple utility for backing up RouterOS configuration.

confinement: strict
grade: stable
base: core18

parts:
  rosbackup:
    plugin: python
    python-version: python3
    source: https://github.com/mharjac/rosbackup.git
    source-type: git

apps:
  rosbackup:
    command: bin/rosbackup
    plugs:
      - network
      - home
    environment:
      LANG: C.UTF-8

